### ISSUE TITLE
How to convert .ge3 ff HEDM data (APS) to H5/HDF5 files which can be imported by hexrd

### ISSUE THREAD

**Issue by minety** [HEXRD/hexrd#178]
Hi,

We just finished some in situ ff HEDM experiments at APS sector-1. 

But having problems of import ff data, I was using the instruction&scripts created by CHESS where they are using .h5 data format as input.

It would be very appreciated that you could help me out.

Thanks,

Tian

**Comment by joelvbernier** [comment]
There are example archiving scripts on Orthros from our recent PUP run here: /clhome/sec1afpup/AFRL/PUP_AFRL_Feb21/run_archiving.py

As far as importing the ge files, there are two options:

1. The GUI can load them directly and you can export an HDF5 or npz style imageseries (good for first look, initial state, but not for batch)
2. using a batch script like my example, which makes use of the generic `image-files` adapter for `imageseries` (see docs [here](https://github.com/HEXRD/hexrd/wiki/ims-load-options))

I would recommend converting FF data from ge3 locally on Orthros or Telemann to npz (`frame-cache`) imageseries, as the compression ratio is 100-1000x.  You can run the GUI locally loading the npz files, or via NoMachine on Telemann if you have access.

**Comment by joelvbernier** [comment]
Here is an example of the YAML file that can be used to load an imageseries for ge3:
```
image-files:
  directory: /s1c/PUP_AFRL_feb21/ge3
  files: "lshr_r4_state0_box_ff_000372.ge3"

options:
  empty-frames: 1  # skip this many frames at the beginning of each get file
  max-frames: 0  # 0: read all; otherwise a max number of frames to read from the files
```
