### ISSUE TITLE
Consider adding pyproject.toml file

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrd#180]
We can use pyproject.toml to specify which dependencies need to be installed before `setup.py` is ran. It could look like this, for instance:

```toml
[build-system]
requires = ["setuptools", "wheel", "numpy"]
```

This would reduce the development install instructions from this:
```python
pip install numpy
pip install -e hexrd
```

to this:
```python
pip install -e hexrd
```

Thoughts? @cjh1 @joelvbernier
