### ISSUE TITLE
Change hkl indexing behavior in seeded search (far-field HEDM)

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrd#452]
We used to live dangerously and have the `active_hkls` specified the indexing (`find-oreintations`) CLI workflow interpreted as direct indices into the `planeData.hkls` as generated.  This was bad for a few reasons:
1. The material is generated on load subject to minimum d-spacing and structure factor cutoff parameters, which can lead to non-sequential exclusions.
2. Non-sequential exclusions can also be saved in the materials archive, and will be merged on load with exclusions from 1.
Since we are selecting from the masked `planeData.hkls` blindly in the CLI (via the yaml config), this can lead to weird inconsistencies.

To remedy this, I propose using the unique `hklID` assigned to each hkl in the master `planeData.hklDataList` instead.  Ideally the config can be modified to take either this or an explicit list of hkls. 

For example, the single GE ruby config will look like:
```
find_orientations:
  orientation_maps:
    # A file name must be specified. If it doesn't exist, one will be created
    file: null

    threshold: 25 # threshold on raw images to build maps
    bin_frames: 1 # how many successive frames to bin. default is 1

    # specify which hkls to use
    # "all", or a list of hkl indices.  Note that the default value of "all"
    # means all hkls that are not marked as excluded in the material definition.
    # can be a list of indices or a list of [h, k, l].
    # active_hkls: [0,1,2,4,6,7]
    active_hkls:
      - [0, 1, 2]
      - [1, 0, 4]
      - [1, 1, 0]
      - [1, 1, 3]
      - [0, 2, 4]
      - [1, 1, 6]
```

@bnmajor , @psavery , and @cjh1 -- This` will finally allow us to clean up https://github.com/HEXRD/hexrdgui/pull/970; we can force it to write out the explicit hkls used as active hkls.
