### ISSUE TITLE
add data directory to imageseries config

### ISSUE THREAD

**Issue by donald-e-boyce** [HEXRD/hexrd#496]
It would be convenient to specify a data directory in the imageseries config file. As it is, either all the data files are in the current directory or they are in a different directory and every panel has the same directory path before the filename. It would nice to have a single directory specified.  For example: this config 
```
image_series:
  format: frame-cache
  data:
    - file: /a/b/c/sample-panel-0.npz
      args: {}
      panel: panel-0  # must match detector key
    - file: /a/b/c/sample-panel-1.npz
      args: {}
      panel: panel-1  # must match detector key
```
could be replaced with 
```
image_series:
  format: frame-cache
  path:  /a/b/c
  data:
    - file: sample-panel-0.npz
      args: {}
      panel: panel-0  # must match detector key
    - file: sample-panel-1.npz
      args: {}
      panel: panel-1  # must match detector key
```
See [hexrd.config.imageseries](https://github.com/HEXRD/hexrd/blob/master/hexrd/config/imageseries.py
)
