### ISSUE TITLE
Find-orientations from CLI not working with fch5

### ISSUE THREAD

**Issue by JoshuaWard201** [HEXRD/hexrd#814]
### Describe the bug

I am trying to run find-orientations from the CLI using a config file that matches that generated when using the "Export full workflow" from the GUI, and has been used in the past. When setting the imageseries file to an fch5, it does not work. The error "Cannot load file containing pickled data" is raised. When I instead use an npz, it works fine.

### Impact

Will eventually cause someone a problem

### Reproduction

Try and run a find-orientations from the CLI using an fch5 file for the image series. A config file can be provided if needed.

### Version

```shell
Latest pre-release of hexrdgui (calling the CLI from this environment).
```

### Affected Workflows

- [ ] core
- [ ] EDD
- [x] HEDM
- [ ] Powder
- [ ] Laue

**Comment by psavery** [comment]
To clarify, if you have an `image_series` section in your hedm config file that looks like this:

```yaml
image_series:
  format: frame-cache
  data:
    - file: some_file.fch5
      args: {}
      panel: eiger  # must match detector key
```

I believe that you can change the `args` to be this:

```yaml
    args:
      style: fch5
```

Let me know if that doesn't work.
